name: 'Setup vcpkg cache'
inputs:
  vcpkg-root-path: 
    description: 'Path where to install vcpkg'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Install vcpkg
      run: |
        echo "Installing vcpkg"

        echo "VCPKG_INSTALLATION_ROOT=${{ inputs.vcpkg-root-path }}" >> $GITHUB_ENV
        echo "PATH=${{ inputs.vcpkg-root-path }}:$PATH" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_BINARY_CACHE=${{ inputs.vcpkg-root-path }}/.cache" >> $GITHUB_ENV
        which vcpkg

        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh --disableMetrics
        mkdir ${{ inputs.vcpkg-root-path }}/.cache

    - name: Env
      run: |
        echo "Vcpkg is installed at: $VCPKG_INSTALLATION_ROOT"
        #echo "======================"
        #env|sort

    # Cache vcpkg
    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.vcpkg-root-path }}/.cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
