name: 'Setup vcpkg cache'
runs:
  using: "composite"
  steps:
    - name: Install vcpkg Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "Installing vcpkg"

        VCPKG_DIR=${{ runner.temp }}/.vcpkg-cache
        echo "VCPKG_DIR=$VCPKG_DIR"

        echo "VCPKG_DEFAULT_BINARY_CACHE=$VCPKG_DIR" >> $GITHUB_ENV
        which vcpkg

        #git clone https://github.com/microsoft/vcpkg.git
        #cd vcpkg
        #./bootstrap-vcpkg.sh --disableMetrics
        mkdir -p $VCPKG_DIR
        cd $VCPKG_DIR
        ls

    - name: cmdll vcpkg Windows
      shell: cmd
      if: runner.os == 'Windows'
      run: |
        echo "Installing vcpkg"

        set VCPKG_DIR=${{ runner.temp }}\.vcpkg-cache

        echo "VCPKG_DIR=%VCPKG_DIR%"

        echo VCPKG_DEFAULT_BINARY_CACHE=%VCPKG_DIR%>> %GITHUB_ENV%
        where vcpkg

        #git clone https://github.com/microsoft/vcpkg.git
        #cd vcpkg
        #call .\bootstrap-vcpkg.bat
        mkdir "%VCPKG_DIR%"
        cd %VCPKG_DIR%
        dir

    - name: Env
      if: False
      shell: bash
      run: |
        echo "Vcpkg is installed at: $VCPKG_INSTALLATION_ROOT"
        echo "VCPKG_DEFAULT_BINARY_CACHE: $VCPKG_DEFAULT_BINARY_CACHE"
        #mkdir $VCPKG_DEFAULT_BINARY_CACHE
        cd $VCPKG_DEFAULT_BINARY_CACHE
        ls
        echo "======================"
        env|sort

    # Cache vcpkg
    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        enableCrossOsArchive: true
        path: ${{ runner.temp }}/.vcpkg-cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
