name: 'Setup vcpkg cache'
inputs:
  vcpkg-root-path: 
    description: 'Path where to install vcpkg'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Install vcpkg
      shell: bash
      run: |
        echo "Installing vcpkg"

        VCPKG_DIR=${{ inputs.vcpkg-root-path }}
        VCPKG_DIR=${VCPKG_DIR//\\//}

        echo "VCPKG_INSTALLATION_ROOT=$VCPKG_DIR" >> $GITHUB_ENV
        echo "PATH=$VCPKG_DIR:$PATH" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_BINARY_CACHE=$VCPKG_DIR/.cache" >> $GITHUB_ENV
        which vcpkg

        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh --disableMetrics
        mkdir $VCPKG_DIR/.cache

    - name: Env
      shell: bash
      run: |
        echo "Vcpkg is installed at: $VCPKG_INSTALLATION_ROOT"
        #echo "======================"
        #env|sort

    # Cache vcpkg
    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.vcpkg-root-path }}/.cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
