name: 'Setup vcpkg cache'
inputs:
  vcpkg-root-path: 
    description: 'Path where to install vcpkg'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Install vcpkg Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "Installing vcpkg"

        VCPKG_DIR=${{ inputs.vcpkg-root-path }}
        echo "before VCPKG_DIR=$VCPKG_DIR"
        VCPKG_DIR="${VCPKG_DIR//\\//}" # Convert backslashes to forward slashes for compatibility
        echo "after VCPKG_DIR=$VCPKG_DIR"

        echo "VCPKG_INSTALLATION_ROOT=$VCPKG_DIR" >> $GITHUB_ENV
        echo "PATH=$VCPKG_DIR:$PATH" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_BINARY_CACHE=$VCPKG_DIR/.cache" >> $GITHUB_ENV
        which vcpkg

        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh --disableMetrics
        mkdir $VCPKG_DIR/.cache

    - name: cmdll vcpkg Windows
      shell: cmd
      if: runner.os == 'Windows'
      run: |
        echo "Installing vcpkg"

        set VCPKG_DIR=%GITHUB_WORKSPACE%/vcpkg

        echo "VCPKG_DIR=%VCPKG_DIR%"

        echo "VCPKG_INSTALLATION_ROOT=%VCPKG_DIR%" >> %GITHUB_ENV%
        echo "PATH=%VCPKG_DIR%;%PATH%" >> %GITHUB_ENV%
        echo "VCPKG_DEFAULT_BINARY_CACHE=%VCPKG_DIR%\.cache" >> %GITHUB_ENV%
        where vcpkg

        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        mkdir %VCPKG_DIR%\.cache
        cd %VCPKG_DIR%\.cache
        dir

    - name: Env
      shell: bash
      run: |
        echo "Vcpkg is installed at: $VCPKG_INSTALLATION_ROOT"
        mkdir $VCPKG_DEFAULT_BINARY_CACHE
        cd $VCPKG_DEFAULT_BINARY_CACHE
        ls
        #echo "======================"
        #env|sort

    # Cache vcpkg
    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        enableCrossOsArchive: true
        path: |
          ${{ inputs.vcpkg-root-path }}/.cache
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
