
name: Build the project
run-name: Build the project on behalf of ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate solution
        run: .\1.generate.solution.cmd

      - name: Build solution
        run: .\2.build.all.cmd
