
name: Build the project
run-name: Build the project on behalf of ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - dev
jobs:
  prepare_params:
    runs-on: windows-latest
    outputs:
      is_release: ${{ steps.define_build_type.outputs.is_release }}
    steps:
      - name: Define build type
        id: define_build_type
        run: |
          "is_release='${{ true }}'" | Out-File -FilePath $Env:GITHUB_OUTPUT

  build_assets:
    needs: prepare_params
    uses: ./.github/workflows/shared_workflow.yml
    with: 
      is_release: ${{ needs.prepare_params.outputs.is_release }}
